import React from 'react'

const Data =  [
    {   id: 1,
        name: "Mark Webber",
        notif: "reacted to your recent post +link My first tournament today!",
        messageImg: null,
        messageContent: "dommy text",
        dateStamp: "1m ago",
        userImg: "./assets/images/avatar-mark-webber.webp",
        isRead: false,      
    },
    {   id: 2,
        name: "Angela Gray",
        notif: "followed you",
        messageImg: null,
        messageContent: "dommy text",
        dateStamp: "5m ago",
        userImg: "./assets/images/avatar-angela-gray.webp",
        isRead: false,       
    },
    {   id: 3,
        name: "Jacob Thompson",
        notif: "has joined your group +link Chess Club",
        messageImg: null,
        messageContent: "dommy text",
        dateStamp: "1 day ago",
        userImg: "./assets/images/avatar-jacob-thompson.webp",
        isRead: false,       
    },
    {   id: 4,
        name: "Rizky Hasanuddin",
        notif: "sent you a private message",
        messageImg: null,
        messageContent: "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
        dateStamp: "5 days ago",
        userImg: "./assets/images/avatar-rizky-hasanuddin.webp",
        isRead: false,       
    },
    {   id: 5,
        name: "Kimberly Smith",
        notif: "commented on your picture",
        messageImg: "./assets/images/image-chess.webp",
        messageContent: "domy text",
        dateStamp: "1 week ago",
        userImg: "./assets/images/avatar-kimberly-smith.webp",
        isRead: false,
    },
    {   id: 6,
        name: "Nathan Peterson",
        notif: "reacted to your recent post +link 5 end-game strategies to increase your win rate",
        messageImg: null,
        messageContent: "dommy text",
        dateStamp: "2 week ago",
        userImg: "./assets/images/avatar-nathan-peterson.webp",
        isRead: false,       
    },
    {   id: 7,
        name: "Anna Kim",
        notif: "left the group +link Chess Club",
        messageImg: null,
        messageContent: "dommy text",
        dateStamp: "2 weeks ago",
        userImg: "./assets/images/avatar-anna-kim.webp",
        isRead: false,       
    },
]

export default Data